-- 코드를 입력하세요
# WITH A AS (SELECT CART_ID, NAME
# FROM CART_PRODUCTS
# WHERE NAME = 'Milk'
# UNION ALL
# SELECT CART_ID, NAME
# FROM CART_PRODUCTS
# WHERE NAME = 'Yogurt'
#            )
           

# SELECT DISTINCT CART_ID
# FROM A
# GROUP BY CART_ID
# HAVING COUNT(CART_ID) >=2 


SELECT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN(
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME ='Milk'
)
AND NAME = 'Yogurt'
ORDER BY CART_ID



# SELECT
# FROM CART_ID
