-- 코드를 작성해주세요
WITH FIRST_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS(
    SELECT A.ID, A.PARENT_ID
    FROM ECOLI_DATA A
    JOIN FIRST_GEN F
    ON A.PARENT_ID = F.ID
)


SELECT ECOLI_DATA.ID
FROM ECOLI_DATA JOIN SECOND_GEN ON ECOLI_DATA.PARENT_ID = SECOND_GEN.ID