SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
LEFT OUTER JOIN(
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    GROUP BY PARENT_ITEM_ID
    HAVING PARENT_ITEM_ID IS NOT NULL
) B
ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE B.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC;