-- 코드를 작성해주세요
WITH PARENT AS(
    SELECT PARENT_ID, COUNT(PARENT_ID) AS COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)



SELECT E.ID, IFNULL(P.COUNT,0) AS CHILD_COUNT
FROM PARENT P
RIGHT OUTER JOIN ECOLI_DATA E
ON E.ID = P.PARENT_ID
ORDER BY ID