-- 코드를 작성해주세요
# SELECT PARENT_ID, COUNT(*) AS COUNT
# FROM ECOLI_DATA
# WHERE PARENT_ID IS NOT NULL
# GROUP BY PARENT_ID


SELECT A.ID, IF(B.COUNT IS NULL, 0, B.COUNT) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT OUTER JOIN (
    SELECT PARENT_ID, COUNT(*) AS COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) AS B
ON A.ID = B.PARENT_ID
ORDER BY ID;
