SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, B.AVG AS SCORE
FROM REST_INFO A
LEFT OUTER JOIN (
SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS AVG
FROM REST_REVIEW
GROUP BY REST_ID
) B
ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE '서울%' AND B.AVG IS NOT NULL
ORDER BY SCORE DESC, FAVORITES DESC;