-- 코드를 입력하세요

# SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, B.AVG AS SCORE
# FROM REST_INFO A
# LEFT OUTER JOIN (
#     SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS AVG
#     FROM REST_REVIEW
#     GROUP BY REST_ID
# ) B
# ON A.REST_ID = B.REST_ID
# WHERE A.ADDRESS LIKE '서울%' AND B.AVG IS NOT NULL
# ORDER BY SCORE DESC, FAVORITES;

# SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS AVG
# FROM REST_REVIEW
# GROUP BY REST_ID

# SELECT * FROM REST_INFO
# WHERE ADDRESS LIKE '서울%'

SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW A
JOIN REST_INFO B ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING B.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, B.FAVORITES DESC
