-- 코드를 입력하세요
SELECT O.YEAR, O.MONTH, U.GENDER, COUNT(DISTINCT(O.USER_ID)) AS USERS
FROM USER_INFO U
RIGHT OUTER JOIN (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
) O
ON U.USER_ID = O.USER_ID
GROUP BY O.YEAR, O.MONTH, U.GENDER
HAVING U.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER
