-- 코드를 입력하세요
SELECT WAREHOUSE_ID,	WAREHOUSE_NAME,	ADDRESS,
case when FREEZER_YN IS NULL THEN 'N'
when FREEZER_YN = 'Y' THEN 'Y'
when FREEZER_YN = 'N' THEN 'N'
END AS FREEZER_YN
from FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE '%경기%'
ORDER BY WAREHOUSE_ID