-- 코드를 입력하세요
# SELECT A.PRODUCT_ID, A.PRODUCT_NAME, 
# FROM FOOD_PRODUCT A
# INNER JOIN FOOD_ORDER B
# ON A.PRODUCT_ID = B.PRODUCT_ID
# WHERE B.PRODUCT_DATE LIKE '2022-05%'


# SELECT PRODUCT_ID, SUM(AMOUNT)
# FROM FOOD_ORDER
# WHERE PRODUCE_DATE LIKE '2022-05%'
# GROUP BY PRODUCT_ID


SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE * B.SUM) AS TOTAL_SALES
FROM FOOD_PRODUCT A
LEFT OUTER JOIN(
    SELECT PRODUCT_ID, SUM(AMOUNT) AS SUM
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY PRODUCT_ID
) B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.SUM IS NOT NULL
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
