-- 코드를 작성해주세요
WITH A AS (
    SELECT EMP_NO, AVG(SCORE) AS AVG
    FROM HR_GRADE
    GROUP BY EMP_NO)
    , B AS(SELECT A.EMP_NO,
CASE WHEN AVG >= 96 THEN 'S'
WHEN AVG >= 90 THEN 'A'
WHEN AVG >= 80 THEN 'B'
ELSE 'C'
END AS 'GRADE'
FROM A)


SELECT H.EMP_NO, H.EMP_NAME, B.GRADE,
CASE WHEN B.GRADE = 'S' THEN H.SAL * 0.2
WHEN B.GRADE = 'A' THEN H.SAL * 0.15
WHEN B.GRADE = 'B' THEN H.SAL * 0.1
ELSE 0
END AS BONUS
FROM HR_EMPLOYEES H
INNER JOIN B
ON H.EMP_NO = B.EMP_NO
ORDER BY EMP_NO


    
