-- 코드를 작성해주세요
# SELECT CODE
# FROM SKILLCODES
# WHERE NAME IN ('Python', 'C#')


SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
) AS S
JOIN DEVELOPERS D
ON S.CODE & D.SKILL_CODE = S.CODE
GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
ORDER BY ID