WITH T1 AS (SELECT MAX(SIZE_OF_COLONY) AS BEST, YEAR(DIFFERENTIATION_DATE) AS YEAR
       FROM ECOLI_DATA 
       GROUP BY YEAR(DIFFERENTIATION_DATE) )
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
       (T1.BEST-A.SIZE_OF_COLONY) AS YEAR_DEV,
       A.ID
FROM ECOLI_DATA A
JOIN T1 ON YEAR(A.DIFFERENTIATION_DATE) = T1.YEAR
ORDER BY YEAR(A.DIFFERENTIATION_DATE) ASC, (T1.BEST-A.SIZE_OF_COLONY) ASC