-- 코드를 작성해주세요
with SIZE as(
    select MAX(SIZE_OF_COLONY) AS MAX, YEAR(DIFFERENTIATION_DATE) AS YEAR
    from ECOLI_DATA
    group by YEAR(DIFFERENTIATION_DATE)
)

select S.YEAR, (S.MAX - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
from ECOLI_DATA A
JOIN SIZE S
ON YEAR(A.DIFFERENTIATION_DATE) = S.YEAR
ORDER BY YEAR, YEAR_DEV