SELECT C.ID, N.FISH_NAME, C.LENGTH
FROM FISH_NAME_INFO N
INNER JOIN (
    SELECT A.ID, A.FISH_TYPE, A.LENGTH
    FROM FISH_INFO A
    INNER JOIN (
        SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) AS B 
    ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.MAX_LENGTH
) AS C
ON N.FISH_TYPE = C.FISH_TYPE
ORDER BY C.ID;