-- 코드를 작성해주세요


# SELECT EMP_NO, SUM(SCORE) AS SCORE
# FROM HR_GRADE
# WHERE YEAR = '2022'
# GROUP BY EMP_NO

SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
LEFT OUTER JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
WHERE YEAR = '2022'
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1