SELECT
CASE WHEN (GROUP_CONCAT(NAME) LIKE '%Python%' AND MAX(CATEGORY) = 'Front End') THEN 'A'
WHEN GROUP_CONCAT(NAME) LIKE '%C#%' THEN 'B'
WHEN MAX(CATEGORY) = 'Front End' THEN 'C'
ELSE NULL END AS GRADE,
ID,
MIN(EMAIL) EMAIL
FROM DEVELOPERS A
JOIN SKILLCODES B
ON A.SKILL_CODE & B.CODE = B.CODE
GROUP BY ID
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;
